import { fluxTwoPrice, gptImagePrice } from './price-rules'
import type { ImageModel } from './types'

/**
 * The image models Umber can drive.
 *
 * Capabilities and prices are transcribed by hand from each vendor's own
 * documentation: a bare number where the vendor charges one rate however big
 * the image, a table where it charges per resolution tier, and a rule from
 * `price-rules` for the two that genuinely compute it. What a run costs is
 * still an estimate, since only the provider can bill it, but no figure here
 * is scaled or guessed off another. Keep entries newest-first per provider.
 */
export const IMAGE_MODELS: readonly ImageModel[] = [
    {
        id: 'nano-banana-2',
        name: 'Nano Banana 2',
        provider: 'google',
        kind: 'image',
        releasedOn: '2026-05-28',
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'],
        resolutions: ['1K', '2K', '4K'],
        maxOutputs: 4,
        pricePerImage: { '1K': 0.067, '2K': 0.101, '4K': 0.151 },
    },
    {
        id: 'nano-banana-pro',
        name: 'Nano Banana Pro',
        provider: 'google',
        kind: 'image',
        releasedOn: '2025-11-20',
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'],
        resolutions: ['1K', '2K', '4K'],
        maxOutputs: 4,
        pricePerImage: { '1K': 0.134, '2K': 0.134, '4K': 0.24 },
    },
    {
        id: 'nano-banana',
        name: 'Nano Banana',
        provider: 'google',
        kind: 'image',
        releasedOn: '2025-08-26',
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'],
        resolutions: ['1K'],
        maxOutputs: 4,
        pricePerImage: 0.039,
    },
    // The GPT Image family: OpenAI bills these by output tokens, which fall out
    // of the quality tier and the exact pixel grid, so their prices are
    // computed rather than quoted. A wide 4K frame really is cheaper than a
    // 2K square.
    {
        id: 'gpt-image-2',
        name: 'GPT Image 2',
        provider: 'openai',
        kind: 'image',
        releasedOn: '2026-04-21',
        // Free-form sizes up to a 3:1 ratio and ~8.3MP, so everything the
        // composer offers short of nothing — 21:9 included.
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'],
        resolutions: ['1K', '2K', '4K'],
        maxOutputs: 4,
        pricePerImage: gptImagePrice('gpt-image-2', 'low'),
        quality: {
            options: ['low', 'medium', 'high'],
            pricePerImage: {
                low: gptImagePrice('gpt-image-2', 'low'),
                medium: gptImagePrice('gpt-image-2', 'medium'),
                high: gptImagePrice('gpt-image-2', 'high'),
            },
        },
    },
    {
        id: 'gpt-image-1-5',
        name: 'GPT Image 1.5',
        provider: 'openai',
        kind: 'image',
        releasedOn: '2025-12-16',
        aspectRatios: ['1:1', '3:2', '2:3'],
        resolutions: ['1K'],
        maxOutputs: 4,
        pricePerImage: gptImagePrice('gpt-image-1-5', 'low'),
        quality: {
            options: ['low', 'medium', 'high'],
            pricePerImage: {
                low: gptImagePrice('gpt-image-1-5', 'low'),
                medium: gptImagePrice('gpt-image-1-5', 'medium'),
                high: gptImagePrice('gpt-image-1-5', 'high'),
            },
        },
    },
    {
        id: 'gpt-image-1-mini',
        name: 'GPT Image 1 Mini',
        provider: 'openai',
        kind: 'image',
        releasedOn: '2025-10-06',
        aspectRatios: ['1:1', '3:2', '2:3'],
        resolutions: ['1K'],
        maxOutputs: 4,
        pricePerImage: gptImagePrice('gpt-image-1-mini', 'low'),
        quality: {
            options: ['low', 'medium', 'high'],
            pricePerImage: {
                low: gptImagePrice('gpt-image-1-mini', 'low'),
                medium: gptImagePrice('gpt-image-1-mini', 'medium'),
                high: gptImagePrice('gpt-image-1-mini', 'high'),
            },
        },
    },
    {
        id: 'gpt-image-1',
        name: 'GPT Image 1',
        provider: 'openai',
        kind: 'image',
        releasedOn: '2025-04-23',
        aspectRatios: ['1:1', '3:2', '2:3'],
        resolutions: ['1K'],
        maxOutputs: 4,
        pricePerImage: gptImagePrice('gpt-image-1', 'low'),
        quality: {
            options: ['low', 'medium', 'high'],
            pricePerImage: {
                low: gptImagePrice('gpt-image-1', 'low'),
                medium: gptImagePrice('gpt-image-1', 'medium'),
                high: gptImagePrice('gpt-image-1', 'high'),
            },
        },
    },
    {
        id: 'flux-2-pro',
        name: 'FLUX.2 [pro]',
        provider: 'blackForestLabs',
        kind: 'image',
        releasedOn: '2025-11-25',
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'],
        resolutions: ['1K', '2K'],
        maxOutputs: 4,
        pricePerImage: fluxTwoPrice,
    },
    {
        id: 'flux-1-kontext-pro',
        name: 'FLUX.1 Kontext [pro]',
        provider: 'blackForestLabs',
        kind: 'image',
        releasedOn: '2025-05-29',
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'],
        resolutions: ['1K'],
        maxOutputs: 4,
        pricePerImage: 0.04,
    },
    {
        id: 'flux-pro-1-1',
        name: 'FLUX 1.1 [pro]',
        provider: 'blackForestLabs',
        kind: 'image',
        releasedOn: '2024-10-02',
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'],
        resolutions: ['1K'],
        maxOutputs: 4,
        pricePerImage: 0.04,
    },
    {
        id: 'seedream-4-5',
        name: 'Seedream 4.5',
        provider: 'bytedance',
        kind: 'image',
        releasedOn: '2025-12-18',
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16'],
        // 4.5 has a pixel floor above the whole 1K tier, which 4.0 still has.
        resolutions: ['2K', '4K'],
        maxOutputs: 4,
        pricePerImage: 0.04,
    },
    {
        id: 'seedream-4',
        name: 'Seedream 4.0',
        provider: 'bytedance',
        kind: 'image',
        releasedOn: '2025-09-09',
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16'],
        resolutions: ['1K', '2K', '4K'],
        maxOutputs: 4,
        pricePerImage: 0.03,
    },
    {
        id: 'qwen-image',
        name: 'Qwen Image',
        provider: 'alibaba',
        kind: 'image',
        releasedOn: '2025-08-05',
        // The shapes Qwen-Image-Plus actually renders; anything else would be
        // silently snapped to one of these.
        aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16'],
        resolutions: ['1K'],
        maxOutputs: 4,
        pricePerImage: 0.03,
    },
    {
        id: 'kling-image-2-1',
        name: 'Kling Image 2.1',
        provider: 'kuaishou',
        kind: 'image',
        releasedOn: '2025-05-10',
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'],
        resolutions: ['1K', '2K'],
        maxOutputs: 4,
        pricePerImage: 0.014,
        pricePerImageFromImage: 0.028,
    },
    {
        id: 'gen-4-image',
        name: 'Gen-4 Image',
        provider: 'runway',
        kind: 'image',
        releasedOn: '2025-03-31',
        aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16', '21:9'],
        resolutions: ['1K', '2K'],
        maxOutputs: 4,
        pricePerImage: { '1K': 0.05, '2K': 0.08 },
    },
    // Ideogram prices by rendering speed, which is what its quality tiers are.
    {
        id: 'ideogram-v4',
        name: 'Ideogram 4.0',
        provider: 'ideogram',
        kind: 'image',
        releasedOn: '2026-06-03',
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16'],
        resolutions: ['1K'],
        maxOutputs: 4,
        pricePerImage: 0.03,
        quality: {
            options: ['low', 'medium', 'high'],
            pricePerImage: { low: 0.03, medium: 0.06, high: 0.1 },
        },
    },
    {
        id: 'ideogram-v3',
        name: 'Ideogram V3',
        provider: 'ideogram',
        kind: 'image',
        releasedOn: '2025-03-26',
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16'],
        resolutions: ['1K'],
        maxOutputs: 4,
        pricePerImage: 0.03,
        quality: {
            options: ['low', 'medium', 'high'],
            pricePerImage: { low: 0.03, medium: 0.06, high: 0.09 },
        },
    },
    {
        id: 'recraft-v4-1',
        name: 'Recraft V4.1',
        provider: 'recraft',
        kind: 'image',
        releasedOn: '2026-02-12',
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16'],
        resolutions: ['1K'],
        maxOutputs: 4,
        pricePerImage: 0.035,
    },
    {
        id: 'recraft-v3',
        name: 'Recraft V3',
        provider: 'recraft',
        kind: 'image',
        releasedOn: '2024-10-30',
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16'],
        resolutions: ['1K'],
        maxOutputs: 4,
        pricePerImage: 0.04,
    },
]
