import type { ImageModel } from './types'

/**
 * The image models Umber can drive.
 *
 * Capabilities and prices are transcribed by hand from each vendor's public
 * documentation and are approximations — the price shown in the composer is an
 * estimate, and none of this is authoritative until the provider integrations
 * report their own limits. Keep entries newest-first within a provider.
 */
export const IMAGE_MODELS: readonly ImageModel[] = [
    {
        id: 'nano-banana-pro',
        name: 'Nano Banana Pro',
        provider: 'google',
        kind: 'image',
        releasedOn: '2025-11-20',
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16'],
        resolutions: ['1K', '2K', '4K'],
        maxOutputs: 4,
        pricePerImage: 0.14,
    },
    {
        id: 'nano-banana',
        name: 'Nano Banana',
        provider: 'google',
        kind: 'image',
        releasedOn: '2025-08-26',
        aspectRatios: ['1:1', '3:2', '2:3', '16:9', '9:16'],
        resolutions: ['1K', '2K'],
        maxOutputs: 4,
        pricePerImage: 0.039,
    },
    {
        id: 'imagen-4-ultra',
        name: 'Imagen 4 Ultra',
        provider: 'google',
        kind: 'image',
        releasedOn: '2025-06-24',
        aspectRatios: ['1:1', '3:4', '4:3', '16:9', '9:16'],
        resolutions: ['1K', '2K'],
        maxOutputs: 4,
        pricePerImage: 0.06,
    },
    // The GPT Image family: a size is derived from aspect ratio and resolution
    // at request time, and cost tracks the quality tier rather than the pixel
    // count — hence the per-tier price tables.
    {
        id: 'gpt-image-2',
        name: 'GPT Image 2',
        provider: 'openai',
        kind: 'image',
        releasedOn: '2026-04-21',
        // Free-form sizes up to a 3:1 ratio and ~8.3MP, so everything the
        // composer offers short of nothing — 21:9 included.
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'],
        resolutions: ['1K', '2K', '4K'],
        maxOutputs: 4,
        pricePerImage: 0.006,
        quality: {
            options: ['low', 'medium', 'high'],
            pricePerImage: { low: 0.006, medium: 0.053, high: 0.211 },
        },
    },
    {
        id: 'gpt-image-1-5',
        name: 'GPT Image 1.5',
        provider: 'openai',
        kind: 'image',
        releasedOn: '2025-12-16',
        aspectRatios: ['1:1', '3:2', '2:3'],
        resolutions: ['1K'],
        maxOutputs: 4,
        pricePerImage: 0.009,
        quality: {
            options: ['low', 'medium', 'high'],
            pricePerImage: { low: 0.009, medium: 0.034, high: 0.133 },
        },
    },
    {
        id: 'gpt-image-1-mini',
        name: 'GPT Image 1 Mini',
        provider: 'openai',
        kind: 'image',
        releasedOn: '2025-10-06',
        aspectRatios: ['1:1', '3:2', '2:3'],
        resolutions: ['1K'],
        maxOutputs: 4,
        pricePerImage: 0.005,
        quality: {
            options: ['low', 'medium', 'high'],
            pricePerImage: { low: 0.005, medium: 0.011, high: 0.036 },
        },
    },
    {
        id: 'gpt-image-1',
        name: 'GPT Image 1',
        provider: 'openai',
        kind: 'image',
        releasedOn: '2025-04-23',
        aspectRatios: ['1:1', '3:2', '2:3'],
        resolutions: ['1K'],
        maxOutputs: 4,
        pricePerImage: 0.011,
        quality: {
            options: ['low', 'medium', 'high'],
            pricePerImage: { low: 0.011, medium: 0.042, high: 0.167 },
        },
    },
    {
        id: 'flux-2-pro',
        name: 'FLUX.2 [pro]',
        provider: 'blackForestLabs',
        kind: 'image',
        releasedOn: '2025-11-25',
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'],
        resolutions: ['1K', '2K', '4K'],
        maxOutputs: 4,
        pricePerImage: 0.05,
    },
    {
        id: 'flux-1-kontext-pro',
        name: 'FLUX.1 Kontext [pro]',
        provider: 'blackForestLabs',
        kind: 'image',
        releasedOn: '2025-05-29',
        aspectRatios: ['1:1', '3:2', '2:3', '16:9', '9:16'],
        resolutions: ['1K', '2K'],
        maxOutputs: 4,
        pricePerImage: 0.04,
    },
    {
        id: 'flux-1-schnell',
        name: 'FLUX.1 [schnell]',
        provider: 'blackForestLabs',
        kind: 'image',
        releasedOn: '2024-08-01',
        aspectRatios: ['1:1', '3:2', '2:3', '16:9', '9:16'],
        resolutions: ['1K'],
        maxOutputs: 4,
        pricePerImage: 0.003,
    },
    {
        id: 'seedream-4',
        name: 'Seedream 4.0',
        provider: 'bytedance',
        kind: 'image',
        releasedOn: '2025-09-09',
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16'],
        resolutions: ['1K', '2K', '4K'],
        maxOutputs: 4,
        pricePerImage: 0.03,
    },
    {
        id: 'qwen-image',
        name: 'Qwen Image',
        provider: 'alibaba',
        kind: 'image',
        releasedOn: '2025-08-05',
        aspectRatios: ['1:1', '3:2', '2:3', '16:9', '9:16'],
        resolutions: ['1K', '2K'],
        maxOutputs: 4,
        pricePerImage: 0.02,
    },
    {
        id: 'gen-4-image',
        name: 'Gen-4 Image',
        provider: 'runway',
        kind: 'image',
        releasedOn: '2025-03-31',
        aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16', '21:9'],
        resolutions: ['1K', '2K'],
        maxOutputs: 4,
        pricePerImage: 0.08,
    },
    {
        id: 'photon-2',
        name: 'Photon 2',
        provider: 'luma',
        kind: 'image',
        releasedOn: '2025-10-07',
        aspectRatios: ['1:1', '3:2', '2:3', '16:9', '9:16', '21:9'],
        resolutions: ['1K', '2K'],
        maxOutputs: 4,
        pricePerImage: 0.019,
    },
    {
        id: 'ideogram-v3',
        name: 'Ideogram V3',
        provider: 'ideogram',
        kind: 'image',
        releasedOn: '2025-03-26',
        aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16'],
        resolutions: ['1K', '2K'],
        maxOutputs: 4,
        pricePerImage: 0.06,
    },
    {
        id: 'recraft-v3',
        name: 'Recraft V3',
        provider: 'recraft',
        kind: 'image',
        releasedOn: '2024-10-30',
        aspectRatios: ['1:1', '3:2', '2:3', '16:9', '9:16'],
        resolutions: ['1K', '2K'],
        maxOutputs: 4,
        pricePerImage: 0.04,
    },
    {
        id: 'stable-diffusion-3-5-large',
        name: 'Stable Diffusion 3.5 Large',
        provider: 'stability',
        kind: 'image',
        releasedOn: '2024-10-22',
        aspectRatios: ['1:1', '3:2', '2:3', '16:9', '9:16'],
        resolutions: ['1K'],
        maxOutputs: 4,
        pricePerImage: 0.035,
    },
]
