import type { VideoModel } from './types'

/**
 * The video models Umber can drive. Same caveats as the image catalog: clip
 * lengths, resolutions and prices are transcribed by hand from public docs and
 * are estimates until the provider integrations report their own limits.
 */
export const VIDEO_MODELS: readonly VideoModel[] = [
    {
        id: 'veo-3-1',
        name: 'Veo 3.1',
        provider: 'google',
        kind: 'video',
        releasedOn: '2025-10-15',
        aspectRatios: ['16:9', '9:16'],
        resolutions: ['720p', '1080p', '4K'],
        durations: { kind: 'list', seconds: [4, 6, 8] },
        pricePerSecond: 0.4,
    },
    {
        id: 'veo-3-1-fast',
        name: 'Veo 3.1 Fast',
        provider: 'google',
        kind: 'video',
        releasedOn: '2026-06-30',
        aspectRatios: ['16:9', '9:16'],
        resolutions: ['720p', '1080p', '4K'],
        durations: { kind: 'list', seconds: [4, 6, 8] },
        pricePerSecond: 0.1,
    },
    {
        id: 'sora-2-pro',
        name: 'Sora 2 Pro',
        provider: 'openai',
        kind: 'video',
        releasedOn: '2025-09-30',
        aspectRatios: ['16:9', '9:16'],
        resolutions: ['720p', '1080p'],
        durations: { kind: 'list', seconds: [4, 8, 12] },
        pricePerSecond: 0.3,
    },
    {
        id: 'sora-2',
        name: 'Sora 2',
        provider: 'openai',
        kind: 'video',
        releasedOn: '2025-09-30',
        aspectRatios: ['16:9', '9:16'],
        resolutions: ['720p'],
        durations: { kind: 'list', seconds: [4, 8, 12] },
        pricePerSecond: 0.1,
    },
    {
        id: 'kling-2-6',
        name: 'Kling 2.6',
        provider: 'kuaishou',
        kind: 'video',
        releasedOn: '2025-12-10',
        aspectRatios: ['16:9', '9:16', '1:1'],
        resolutions: ['720p', '1080p'],
        durations: { kind: 'list', seconds: [5, 10] },
        pricePerSecond: 0.042,
    },
    {
        id: 'kling-2-5-turbo',
        name: 'Kling 2.5 Turbo',
        provider: 'kuaishou',
        kind: 'video',
        releasedOn: '2025-09-23',
        aspectRatios: ['16:9', '9:16', '1:1'],
        resolutions: ['720p', '1080p'],
        durations: { kind: 'list', seconds: [5, 10] },
        pricePerSecond: 0.042,
    },
    {
        id: 'seedance-2-0',
        name: 'Seedance 2.0',
        provider: 'bytedance',
        kind: 'video',
        releasedOn: '2026-01-22',
        aspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4', '21:9'],
        resolutions: ['480p', '720p', '1080p', '4K'],
        durations: { kind: 'range', min: 4, max: 15, step: 1 },
        pricePerSecond: 0.07,
    },
    {
        id: 'seedance-1-pro',
        name: 'Seedance 1.0 Pro',
        provider: 'bytedance',
        kind: 'video',
        releasedOn: '2025-06-16',
        aspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4', '21:9'],
        resolutions: ['480p', '720p', '1080p'],
        durations: { kind: 'range', min: 2, max: 12, step: 1 },
        pricePerSecond: 0.024,
    },
    {
        id: 'hailuo-2-3',
        name: 'Hailuo 2.3',
        provider: 'minimax',
        kind: 'video',
        releasedOn: '2025-10-21',
        aspectRatios: ['16:9'],
        resolutions: ['720p', '1080p'],
        durations: { kind: 'list', seconds: [6, 10] },
        pricePerSecond: 0.047,
    },
    {
        id: 'hailuo-2-3-fast',
        name: 'Hailuo 2.3 Fast',
        provider: 'minimax',
        kind: 'video',
        releasedOn: '2025-10-21',
        aspectRatios: ['16:9'],
        resolutions: ['720p', '1080p'],
        durations: { kind: 'list', seconds: [6, 10] },
        pricePerSecond: 0.032,
    },
    {
        id: 'wan-2-6',
        name: 'Wan 2.6',
        provider: 'alibaba',
        kind: 'video',
        releasedOn: '2026-01-08',
        aspectRatios: ['16:9', '9:16', '1:1'],
        resolutions: ['480p', '720p', '1080p'],
        durations: { kind: 'list', seconds: [5, 10] },
        pricePerSecond: 0.05,
    },
    {
        id: 'gen-4-5',
        name: 'Gen-4.5',
        provider: 'runway',
        kind: 'video',
        releasedOn: '2025-12-02',
        aspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4', '21:9'],
        resolutions: ['720p'],
        durations: { kind: 'list', seconds: [5, 8, 10] },
        pricePerSecond: 0.12,
    },
    {
        id: 'gen-4-turbo',
        name: 'Gen-4 Turbo',
        provider: 'runway',
        kind: 'video',
        releasedOn: '2025-04-01',
        aspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4', '21:9'],
        resolutions: ['720p'],
        durations: { kind: 'list', seconds: [5, 10] },
        pricePerSecond: 0.05,
    },
    {
        id: 'ray-3-2',
        name: 'Ray 3.2',
        provider: 'luma',
        kind: 'video',
        releasedOn: '2026-05-12',
        aspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4', '21:9'],
        resolutions: ['720p', '1080p'],
        durations: { kind: 'list', seconds: [5, 10] },
        pricePerSecond: 0.06,
    },
    {
        id: 'pixverse-c1',
        name: 'PixVerse C1',
        provider: 'pixverse',
        kind: 'video',
        releasedOn: '2026-06-18',
        aspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4', '3:2', '2:3', '21:9'],
        resolutions: ['720p', '1080p'],
        durations: { kind: 'range', min: 1, max: 15, step: 1 },
        pricePerSecond: 0.1,
    },
    {
        id: 'pixverse-v6',
        name: 'PixVerse V6',
        provider: 'pixverse',
        kind: 'video',
        releasedOn: '2026-01-08',
        aspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4', '3:2', '2:3', '21:9'],
        resolutions: ['720p', '1080p'],
        durations: { kind: 'range', min: 1, max: 15, step: 1 },
        pricePerSecond: 0.09,
    },
    {
        id: 'ltx-2-5-pro',
        name: 'LTX-2.5 Pro',
        provider: 'lightricks',
        kind: 'video',
        releasedOn: '2026-05-20',
        aspectRatios: ['16:9', '9:16'],
        resolutions: ['720p', '1080p'],
        durations: { kind: 'list', seconds: [6, 8, 10] },
        pricePerSecond: 0.12,
    },
    {
        id: 'ltx-2-5-fast',
        name: 'LTX-2.5 Fast',
        provider: 'lightricks',
        kind: 'video',
        releasedOn: '2026-05-20',
        aspectRatios: ['16:9', '9:16'],
        resolutions: ['720p', '1080p', '4K'],
        durations: { kind: 'list', seconds: [6, 8, 10] },
        pricePerSecond: 0.09,
    },
]
